### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by ritermargariter** [alexeytatarchuk/voting#1]
When I run docker swarm init I get an error:

`Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on different interfaces (192.168.130.117 on enp1s0 and 192.168.130.89 on wlp2s0) - specify one with --advertise-addr`

Could you help me?

**Comment by alexeytatarchuk** [comment]
If you have multiple addresses on different interfaces, you have to specify one with --advertise-addr
